name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions üöÄ
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "üí° The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "üñ•Ô∏è The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "üçè This job's status is ${{ job.status }}."Google Translate

English - Detected

English

Spanish

French

English

Spanish

Arabic
<!DOCTYPE HTML>
<html lang="en" >






<head>
    



<meta name="shc-search-version" content="v2"/>

<link rel="preload" href="/etc/clientlibs/shc/fonts/fonts/Source-Sans-Pro-regular/Source-Sans-Pro-regular.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="/etc/clientlibs/shc/fonts/fonts/Source-Sans-Pro-300/Source-Sans-Pro-300.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="/etc/clientlibs/shc/fonts/fonts/Source-Sans-Pro-600/Source-Sans-Pro-600.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="/etc/clientlibs/shc/fonts/fonts/Source-Sans-Pro-700/Source-Sans-Pro-700.woff2" as="font" type="font/woff2" crossorigin>

<link rel="preconnect" href="https://sp1004f3b2.guided.ss-omtrdc.net"> 
<link rel="preconnect" href="https://smetrics.stanfordhealthcare.org">
<link rel="preconnect" href="https://www.google-analytics.com">
<link rel="preconnect" href="https://www.googletagmanager.com">
<link rel="preconnect" href="https://www.youtube.com">
<link rel="preconnect" href="https://s.ytimg.com">
<link rel="preconnect" href="https://adservice.google.com">
<link rel="preconnect" href="https://device.4seeresults.com">
<link rel="preconnect" href="https://assets.adobedtm.com">
<script>
function shcDOMContentLoaded(fn) {
  if (document.readyState === "complete" || document.readyState === "interactive") { setTimeout(fn, 1); } else { document.addEventListener("DOMContentLoaded", fn); }
}
</script>
    







  
  
  
  
  
  
  <!-- Google Tag Manager -->
  <script>
    (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
      new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
      j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
      'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-PND43V');
  </script>
  <!-- End Google Tag Manager -->

    <!-- include all the meta tags that need to be on all pages here -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge" >
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <link rel="icon" type="image/gif" href="/etc/clientlibs/shc/main/img/favicon.gif"/>
    




    <script>CQURLInfo={"requestPath":"/content/shc/en/second-opinion/general-form","extension":"html","selectors":[],"systemId":"02e435de-69e3-4bfe-9250-da2816f306e4","runModes":"som,s7connect,crx3,production,nosamplecontent,publish,crx3tar"};</script>
<link rel="stylesheet" href="/etc/clientlibs/shc/all.lc-1717540219062-lc.min.4d2b1bc689c14845a8370efdd7118126.css" type="text/css">


    
        <meta name="robots" content="noindex, nofollow">
    

    
    
        
        
        
        
        
    
    
        
        
    
    
    

    <meta name="sp_specialties" content="" > 
    <meta name="sp_pageName" content="second-opinion:general-form">
    <meta name="Language" content="en"/>
    <meta name="Location" content="us"/>

    
    
    
    <meta name="sp_isPatientEd" content="false">

    <!-- Disable native phone number recognition in iOS devices //-->
    <meta name="format-detection" content="telephone=no" />
    

    <!-- perform all standard logic that needs to be on all pages here -->
    
    
    
    
    
    
    
    

    
    

    
    
    

    

    
    
        
        
                                         
    

    <!-- Override the finalTitle with authored pageTitle property, when populated -->
    

    <!-- Override finalTitle with SEO search results title, if populated -->
    

    
        
        
            
                
                
                
                    <title>Get a Second Opinion | Stanford Health Care</title>
                
            
        
    
    <!-- include all page specific meta tags in customheadlogic.jsp scripts -->
    <!-- perform all page specific logic in customheadlogic.jsp scripts -->
    



    













    
    
        
        <meta name="description" content="Learn how Stanford Health Care brings together leading-edge technology, innovative research, and world-renowned experts to meet your unique needs.">
    

    



<script type="text/javascript">s_preLoad = (new Date()).getTime();</script>







<script type="text/javascript">
    var SHC = SHC || {};
    var GLOBAL_SPURL_OBJECT = "//sp1004f3b2.guided.ss-omtrdc.net";
    var HOME_PAGE_PATH = "/content/shc/en";
    var GLOBAL_MICROSITE_SRC = "";
    var GLOBAL_SEARCH_RESULTS_TEMPLATE = "/apps/shc/templates/searchresults";
    var GLOBAL_LOCATIONS_TEMPLATE = "/apps/shc/templates/location";
    var DOCTOR_DIRECTORY_PAGE = "search-results.doctors.html";
    var DOCTOR_DIRECTORY_PATH = "/content/shc/en/search-results.doctors.html";
</script>



<script type="text/javascript">
  var CLINIC_DIRECTORY_PATH = "/content/shc/en/search-results.clinics.html";
  var CLINIC_DIRECTORY_PAGE = "search-results.clinic
5,000 / 5,000
<!DOCTYPE HTML>
<html lang="ar">






<ÿßŸÑÿ±ÿ£ÿ≥>




<meta name="shc-search-version" content="v2"/>

<link rel="preload" href="/etc/clientlibs/shc/fonts/fonts/Source-Sans-Pro-regular/Source-Sans-Pro-regular.woff2" as="font" type="font/woff2 "ŸÉÿ±Ÿàÿ≥ ÿ£Ÿàÿ±Ÿäÿ¨ŸäŸÜ>
<link rel="preload" href="/etc/clientlibs/shc/fonts/fonts/Source-Sans-Pro-300/Source-Sans-Pro-300.woff2" as="font" type="font/woff2 "ŸÉÿ±Ÿàÿ≥ ÿ£Ÿàÿ±Ÿäÿ¨ŸäŸÜ>
<link rel="preload" href="/etc/clientlibs/shc/fonts/fonts/Source-Sans-Pro-600/Source-Sans-Pro-600.woff2" as="font" type="font/woff2 "ŸÉÿ±Ÿàÿ≥ ÿ£Ÿàÿ±Ÿäÿ¨ŸäŸÜ>
<link rel="preload" href="/etc/clientlibs/shc/fonts/fonts/Source-Sans-Pro-700/Source-Sans-Pro-700.woff2" as="font" type="font/woff2 "ŸÉÿ±Ÿàÿ≥ ÿ£Ÿàÿ±Ÿäÿ¨ŸäŸÜ>

<link rel="preconnect" href="https://sp1004f3b2.guided.ss-omtrdc.net">
<link rel="preconnect" href="https://smetrics.stanfordhealthcare.org">
<link rel="preconnect" href="https://www.google-analytics.com">
<link rel="preconnect" href="https://www.googletagmanager.com">
<link rel="preconnect" href="https://www.youtube.com">
<link rel="preconnect" href="https://s.ytimg.com">
<link rel="preconnect" href="https://adservice.google.com">
<link rel="preconnect" href="https://device.4seeresults.com">
<link rel="preconnect" href="https://assets.adobedtm.com">
<ÿßŸÑŸÜÿµ ÿßŸÑÿ®ÿ±ŸÖÿ¨Ÿä>
ÿßŸÑÿØÿßŸÑÿ© shcDOMContentLoaded(fn) {
 if (document.readyState === "Complete" || document.readyState === "interactive") { setTimeout(fn, 1); } else { document.addEventListener("DOMContentLoaded", fn); }
}
</script>














 <!-- ÿ®ÿ±ŸÜÿßŸÖÿ¨ ÿ•ÿØÿßÿ±ÿ© ÿßŸÑÿπŸÑÿßŸÖÿßÿ™ ŸÖŸÜ Google -->
 <ÿßŸÑŸÜÿµ ÿßŸÑÿ®ÿ±ŸÖÿ¨Ÿä>
 (Ÿàÿ∏ŸäŸÅÿ©(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
 new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
 j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
 'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
 })(window,document,'script','dataLayer','GTM-PND43V');
 </script>
 <!-- ÿ•ŸÜŸáÿßÿ° ÿ®ÿ±ŸÜÿßŸÖÿ¨ ÿ•ÿØÿßÿ±ÿ© ÿßŸÑÿπŸÑÿßŸÖÿßÿ™ ŸÖŸÜ Google -->

 <!-- ŸÇŸÖ ÿ®ÿ™ÿ∂ŸÖŸäŸÜ ÿ¨ŸÖŸäÿπ ÿßŸÑÿπŸÑÿßŸÖÿßÿ™ ÿßŸÑŸàÿµŸÅŸäÿ© ÿßŸÑÿ™Ÿä Ÿäÿ¨ÿ® ÿ£ŸÜ ÿ™ŸÉŸàŸÜ ŸÅŸä ÿ¨ŸÖŸäÿπ ÿßŸÑÿµŸÅÿ≠ÿßÿ™ ŸáŸÜÿß -->
 <meta http-equiv="X-UA-Compatible" content="IE=edge" >
 <meta name="viewport" content="width=device-widthÿå ÿßŸÑŸÖŸÇŸäÿßÿ≥ ÿßŸÑÿ£ŸàŸÑŸä=1.0ÿå ÿßŸÑÿ≠ÿØ ÿßŸÑÿ£ÿØŸÜŸâ ŸÑŸÑŸÖŸÇŸäÿßÿ≥=1.0">
 <link rel="icon" type="image/gif" href="/etc/clientlibs/shc/main/img/favicon.gif"/>





 <script>CQURLInfo={"requestPath":":/content/shc/en/ Second-opinion/general-form"ÿå "extension": "html"ÿå "selector":[]ÿå "systemId": "02e435de-69e3" -4bfe-9250-da2816f306e4"ÿå "runModes": "somÿås7connectÿåcrx3ÿåproductionÿånosamplecontentÿåpublishÿåcrx3tar"};</script>
<link rel="stylesheet" href="/etc/clientlibs/shc/all.lc-1717540219062-lc.min.4d2b1bc689c14845a8370efdd7118126.css" type="text/css">



 <meta name="robots" content="noindex, nofollow">

















 < ÿßÿ≥ŸÖ ÿßŸÑÿ™ÿπÿ±ŸäŸÅ = "sp_specialties" ÿßŸÑŸÖÿ≠ÿ™ŸàŸâ = "" >
 <meta name="sp_pageName" content="ÿßŸÑÿ±ÿ£Ÿä ÿßŸÑÿ´ÿßŸÜŸä:ÿßŸÑŸÜŸÖŸàÿ∞ÿ¨ ÿßŸÑÿπÿßŸÖ">
 <meta name="Language" content="en"/>
 <meta name="Location" content="us"/>




 <meta name="sp_isPatientEd" content="false">

 <!-- ÿ™ÿπÿ∑ŸäŸÑ ÿßŸÑÿ™ÿπÿ±ŸÅ ÿπŸÑŸâ ÿ±ŸÇŸÖ ÿßŸÑŸáÿßÿ™ŸÅ ÿßŸÑÿ£ÿµŸÑŸä ŸÅŸä ÿ£ÿ¨Ÿáÿ≤ÿ© iOS //-->
 <meta name="format-detection" content="telephone=no" />


 <!-- ÿ™ŸÜŸÅŸäÿ∞ ŸÉŸÑ ÿßŸÑŸÖŸÜÿ∑ŸÇ ÿßŸÑŸÇŸäÿßÿ≥Ÿä ÿßŸÑÿ∞Ÿä Ÿäÿ¨ÿ® ÿ£ŸÜ ŸäŸÉŸàŸÜ ŸÖŸàÿ¨ŸàÿØŸãÿß ŸÅŸä ÿ¨ŸÖŸäÿπ ÿßŸÑÿµŸÅÿ≠ÿßÿ™ ŸáŸÜÿß -->

























 <!-- ŸÇŸÖ ÿ®ÿ™ÿ¨ÿßŸàÿ≤ FinalTitle ÿ®ÿßÿ≥ÿ™ÿÆÿØÿßŸÖ ÿÆÿßÿµŸäÿ© pageTitle ÿßŸÑŸÖÿ§ŸÑŸÅÿ©ÿå ÿπŸÜÿØ ŸÖŸÑÿ§Ÿáÿß -->


 <!-- ÿ™ÿ¨ÿßŸàÿ≤ ÿπŸÜŸàÿßŸÜ FinalTitle ÿ®ÿßÿ≥ÿ™ÿÆÿØÿßŸÖ ÿπŸÜŸàÿßŸÜ ŸÜÿ™ÿßÿ¶ÿ¨ ÿ®ÿ≠ÿ´ SEOÿå ÿ•ÿ∞ÿß ÿ™ŸÖ ŸÖŸÑÿ§Ÿá -->









 <ÿßŸÑÿπŸÜŸàÿßŸÜ>ÿßÿ≠ÿµŸÑ ÿπŸÑŸâ ÿ±ÿ£Ÿä ÿ´ÿßŸÜŸç | ÿ≥ÿ™ÿßŸÜŸÅŸàÿ±ÿØ ŸÑŸÑÿ±ÿπÿßŸäÿ© ÿßŸÑÿµÿ≠Ÿäÿ©</title>




 <!-- ÿ™ÿ∂ŸÖŸäŸÜ ŸÉÿßŸÅÿ© ÿßŸÑÿπŸÑÿßŸÖÿßÿ™ ÿßŸÑŸàÿµŸÅŸäÿ© ÿßŸÑÿÆÿßÿµÿ© ÿ®ÿßŸÑÿµŸÅÿ≠ÿ© ŸÅŸä ÿßŸÑÿ®ÿ±ÿßŸÖÿ¨ ÿßŸÑŸÜÿµŸäÿ© customheadlogic.jsp -->
 <!-- ÿ™ŸÜŸÅŸäÿ∞ ŸÉŸÑ ÿßŸÑŸÖŸÜÿ∑ŸÇ ÿßŸÑÿÆÿßÿµ ÿ®ÿßŸÑÿµŸÅÿ≠ÿ© ŸÅŸä ÿßŸÑÿ®ÿ±ÿßŸÖÿ¨ ÿßŸÑŸÜÿµŸäÿ© customheadlogic.jsp -->





















 <meta name="description" content="ÿ™ÿπÿ±ŸÅ ÿπŸÑŸâ ŸÉŸäŸÅŸäÿ© ÿØŸÖÿ¨ Stanford Health Care ÿ®ŸäŸÜ ÿßŸÑÿ™ŸÉŸÜŸàŸÑŸàÿ¨Ÿäÿß ÿßŸÑÿ±ÿßÿ¶ÿØÿ© ŸàÿßŸÑÿ£ÿ®ÿ≠ÿßÿ´ ÿßŸÑŸÖÿ®ÿ™ŸÉÿ±ÿ© ŸàÿßŸÑÿÆÿ®ÿ±ÿßÿ° ÿßŸÑŸÖÿ¥ŸáŸàÿ±ŸäŸÜ ÿπÿßŸÑŸÖŸäŸãÿß ŸÑÿ™ŸÑÿ®Ÿäÿ© ÿßÿ≠ÿ™Ÿäÿßÿ¨ÿßÿ™ŸÉ ÿßŸÑŸÅÿ±ŸäÿØÿ©.">






<script type="text/javascript">s_preLoad = (new Date()).getTime();</script>







<ŸÜŸàÿπ ÿßŸÑÿ®ÿ±ŸÜÿßŸÖÿ¨ ÿßŸÑŸÜÿµŸä = "ŸÜÿµ/ÿ¨ÿßŸÅÿß ÿ≥ŸÉÿ±Ÿäÿ®ÿ™">
 ŸÅÿßÿ± SHC = SHC || {};
 var GLOBAL_SPURL_OBJECT = "//sp1004f3b2.guided.ss-omtrdc.net";
 var HOME_PAGE_PATH = "/content/shc/en";
 var GLOBAL_MICROSITE_SRC = "";
 var GLOBAL_SEARCH_RESULTS_TEMPLATE = "/apps/shc/templates/searchresults";
 var GLOBAL_LOCATIONS_TEMPLATE = "/apps/shc/templates/location";
 var DOCTOR_DIRECTORY_PAGE = "search-results.doctors.html";
 var DOCTOR_DIRECTORY_PATH = "/content/shc/en/search-results.doctors.html";
</script>



<ŸÜŸàÿπ ÿßŸÑÿ®ÿ±ŸÜÿßŸÖÿ¨ ÿßŸÑŸÜÿµŸä = "ŸÜÿµ/ÿ¨ÿßŸÅÿß ÿ≥ŸÉÿ±Ÿäÿ®ÿ™">
 var CLINIC_DIRECTORY_PATH = "/content/shc/en/search-results.clinics.html";
 var CLINIC_DIRECTORY_PAGE = "search-results.clinic
<!DOCTYPE HTML>
<html lang="ar">
<alraasa>

<meta name="shc-search-version" content="v2"/>
<link rel="preload" href="/etc/clientlibs/shc/fonts/fonts/Source-Sans-Pro-regular/Source-Sans-Pro-regular.woff2" as="font" type="font/woff2 "krus 'uwrijin>
<link rel="preload" href="/etc/clientlibs/shc/fonts/fonts/Source-Sans-Pro-300/Source-Sans-Pro-300.woff2" as="font" type="font/woff2 "krus 'uwrijin>
<link rel="preload" href="/etc/clientlibs/shc/fonts/fonts/Source-Sans-Pro-600/Source-Sans-Pro-600.woff2" as="font" type="font/woff2 "krus 'uwrijin>
<link rel="preload" href="/etc/clientlibs/shc/fonts/fonts/Source-Sans-Pro-700/Source-Sans-Pro-700.woff2" as="font" type="font/woff2 "krus 'uwrijin>
<link rel="preconnect" href="https://sp1004f3b2.guided.ss-omtrdc.net">
<link rel="preconnect" href="https://smetrics.stanfordhealthcare.org">
<link rel="preconnect" href="https://www.google-analytics.com">
<link rel="preconnect" href="https://www.googletagmanager.com">
<link rel="preconnect" href="https://www.youtube.com">
<link rel="preconnect" href="https://s.ytimg.com">
<link rel="preconnect" href="https://adservice.google.com">
<link rel="preconnect" href="https://device.4seeresults.com">
<link rel="preconnect" href="https://assets.adobedtm.com">
<alnns albarmaji>
aldaalat shcDOMContentLoaded(fn) {
if (document.readyState === "Complete" || document.readyState === "interactive") { setTimeout(fn, 1); } else { document.addEventListener("DOMContentLoaded", fn); }
}
</script>







<!-- barnamaj 'iidarat alealamat min Google -->
<alnns albarmaji>
(wazifatu(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-PND43V');
</script>
<!-- 'iinha' barnamaj 'iidarat alealamat min Google -->
<!-- qum bitadmin jamie alealamat alwasfiat alati yajib 'an takun fi jamie alsafahat huna -->
<meta http-equiv="X-UA-Compatible" content="IE=edge" >
<meta name="viewport" content="width=device-width, almiqyas al'awli=1.0, alhadu al'adnaa lilmiqyasi=1.0">
<link rel="icon" type="image/gif" href="/etc/clientlibs/shc/main/img/favicon.gif"/>

<script>CQURLInfo={"requestPath":":/content/shc/en/ Second-opinion/general-form"ÿå "extension": "html"ÿå "selector":[]ÿå "systemId": "02e435de-69e3" -4bfe-9250-da2816f306e4"ÿå "runModes": "somÿås7connectÿåcrx3ÿåproductionÿånosamplecontentÿåpublishÿåcrx3tar"};</script>
<link rel="stylesheet" href="/etc/clientlibs/shc/all.lc-1717540219062-lc.min.4d2b1bc689c14845a8370efdd7118126.css" type="text/css">

<meta name="robots" content="noindex, nofollow">















< asm altaerif = "sp_specialties" almuhtawaa = "" >
<meta name="sp_pageName" content="alraay althaani:alnnmudhaj aleami">
<meta name="Language" content="en"/>
<meta name="Location" content="us"/>



<meta name="sp_isPatientEd" content="false">
<!-- taetil altaearuf ealaa raqm alhatif al'aslii fi 'ajhizat iOS //-->
<meta name="format-detection" content="telephone=no" />

<!-- tanfidh kuli almantiq alqiasii aladhi yajib 'an yakun mwjwdan fi jamie alsafahat huna -->




















<!-- qum bitajawuz FinalTitle biastikhdam khasiyat pageTitle almualafati, eind malwiha -->

<!-- tajawaz eunwan FinalTitle biastikhdam eunwan natayij bahth SEOÿå 'iidha tama malwuh -->








<aleunwani>ahasul ealaa ray than | stanfurd lilrieayat alsihiyati</title>




<!-- tadmin kafat alealamat alwasfiat alkhasat bialsafhat fi albaramij alnasiyat customheadlogic.jsp -->
<!-- tanfidh kuli almantiq alkhasi bialsafhat fi albaramij alnasiyat customheadlogic.jsp -->





<meta name="description" content="tieraf ealaa kayfiat damj Stanford Health Care bayn altiknulujia alraayidat wal'abhath almubtakarat walkhubara' almashhurin ealmyan litalbiat aihtiajatik alfaridati.">


<script type="text/javascript">s_preLoad = (new Date()).getTime();</script>
<nawe albarnamaj alnisiyi = "nsi/jafa skribt">
far SHC = SHC || {};
var GLOBAL_SPURL_OBJECT = "//sp1004f3b2.guided.ss-omtrdc.net";
var HOME_PAGE_PATH = "/content/shc/en";
var GLOBAL_MICROSITE_SRC = "";
var GLOBAL_SEARCH_RESULTS_TEMPLATE = "/apps/shc/templates/searchresults";
var GLOBAL_LOCATIONS_TEMPLATE = "/apps/shc/templates/location";
var DOCTOR_DIRECTORY_PAGE = "search-results.doctors.html";
var DOCTOR_DIRECTORY_PATH = "/content/shc/en/search-results.doctors.html";
</script>
<nawe albarnamaj alnisiyi = "nsi/jafa skribt">
var CLINIC_DIRECTORY_PATH = "/content/shc/en/search-results.clinics.html";
var CLINIC_DIRECTORY_PAGE = "search-results.clinic
Show less
Send feedback
5,000 character limit. Use the arrows to translate more.

